version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
    networks:
      - shared-network
    depends_on:
      - example_sql

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - shared-network
  
  example_sql:
    image: mysql:5.7
    container_name: example_sql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - shared-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: example_pma
    links:
      - example_sql
    environment:
      PMA_HOST: example_sql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - shared-network

networks:
  shared-network:
volumes:
  dbdata: 